config/routes.rb
Rails.application.routes.draw do
  resources :pins
  devise_for :users
root "pages#home"  
get "about" => "pages#about"

end

app/models/pin.rb
class Pin < ActiveRecord::Base
     belongs_to :user
     has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
     validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def about 
  end 
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]


  def index
    @pins = Pin.all
  end

  def show
  end

  def new
    @pin = current_user.pins.build
  end

  def edit
  end

  def create
    @pin = current_user.pins.build(pin_params)
    if @pin.save
      redirect_to @pin, notice: 'Pin was successfully created.'
    else
      render :new
    end
  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: 'Pin was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @pin.destroy
    redirect_to pins_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find_by(id: params[:id])
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
        def pin_params
      params.require(:pin).permit(:description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <div class="container">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "Pinceles y vino", root_path, class: "navbar-brand" %>
  </div>


  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <% if user_signed_in? %>
        <li><%= link_to "Account Settings", edit_user_registration_path %></li>
          <li>
            <%= link_to new_pin_path do %>
              <span class="icon circle-with-plus"></span> New Pin
            <% end %>
          </li>
        <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

</div><!-- /.container --> 
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Parto</title>
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

</head>
<body>

     <%= render 'layouts/header' %>
     <div class ="container">
     	<% flash.each do |name, msg| %>
     <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
<% end %>



<%= yield %>


     <%= render 'layouts/footer' %>

</body>
</html>

app/views/pages/about.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- These meta tags come first. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Bootstrap Theme Example</title>

    <!-- Include the CSS -->
    <link href="dist/toolkit.min.css" rel="stylesheet">

  </head>
  <body>
   


      <div class="row">
        </div>
    </div>



<div class="block-secondary app-high-praise p-b-0">
  <div class="container">
    <div class="row app-align-center">
      <div class="col-sm-5 col-sm-push-7">
        <h6 class="text-muted text-uppercase">High Praise</h6>
        <h3 class="m-t-0 m-b-md">“Parto.org es una herramienta gratuita para empoderar, brindar apoyo y enseñanza a las comadronas en el interior del país."</h3>
        <p class="m-b-md text-muted">Dr. Emilio Pérez, PHD</p>
        <button class="btn btn-primary btn-lg">Try it now</button>
      </div>
      <div class="col-sm-6 col-sm-pull-5">
        <img src="http://www.elmendolotudo.com.ar/wp-content/uploads/portrait_of_a_senior_doctor_writing_reports_isolated_on_white_background_w640.jpeg?dd8ef2">

      </div>
    </div>
  </div>
</div>

<div class="app-ribbon p-y-lg">
  <div class="container text-center">
    <img src="assets/startup-4.svg">
    <img src="assets/startup-5.svg">
    <img src="assets/startup-6.svg">
    <img src="assets/startup-7.svg">
    <img src="assets/startup-8.svg">
  </div>
</div>

<div class="block-secondary app-block-marketing-grid">
  <div class="container text-center">

    <div class="row m-b-lg">
      <div class="col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2 col-lg-6 col-lg-offset-3">
        <h6 class="text-muted text-uppercase">Inside the machine</h6>
        <h3  class="m-t-0 m-b">It’s not hard to see how we make your life easier every day.</h3>
      </div>
    </div>

    <div class="row app-marketing-grid">
      <div class="col-sm-4 p-x-md m-b-lg">
        <img class="m-b" src="assets/startup-9.svg">
        <p><strong>24/7 support.</strong> We’re always here for you no matter what time of day.</p>
      </div>
      <div class="col-sm-4 p-x-md m-b-lg">
        <img class="m-b" src="assets/startup-10.svg">
        <p><strong>E-commerce.</strong> We automatically handle all sales analytics.</p>
      </div>
      <div class="col-sm-4 p-x-md m-b-lg">
        <img class="m-b" src="assets/startup-11.svg">
        <p><strong>Turnaround.</strong> Our data analysis is distributed, so it processes in seconds.</p>
      </div>
    </div>

    <div class="row app-marketing-grid">
      <div class="col-sm-4 p-x-md m-b-lg">
        <img class="m-b" src="assets/startup-12.svg">
        <p><strong>Rich calculations.</strong> Limitless ways to splice and dice your data.</p>
      </div>
      <div class="col-sm-4 p-x-md m-b-lg">
        <img class="m-b" src="assets/startup-13.svg">
        <p><strong>Mobile apps.</strong> iOS and Android apps available for monitoring.</p>
      </div>
      <div class="col-sm-4 p-x-md m-b-lg">
        <img class="m-b" src="assets/startup-14.svg">
        <p><strong>Secure connections.</strong> Every single request is routed through HTTPS.</p>
      </div>
    </div>
  </div>
</div>

<div class="app-price-plans">
  <div class="container text-center">

    <div class="row m-b-lg">
      <div class="col-sm-8 col-sm-offset-2 col-lg-6 col-lg-offset-3">
        <h6 class="text-muted text-uppercase">Business Talk</h6>
        <h3  class="m-t-0">No plans. We just bump your plan whenever you need it.</h3>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-4 p-x m-b-lg">
        <div class="p-x">
          <h6 class="text-muted text-uppercase m-b">Personal</h6>
          <img class="m-b" src="assets/startup-15.svg">
          <p>Plenty of processing power for any personal projects, big or small.</p>
        </div>

        <ul class="list-unstyled list-bordered text-left m-y-md">
          <li class="p-y"><strong>10k</strong> monthly requests</li>
          <li class="p-y"><strong>9am-5pm</strong> technical supprt</li>
          <li class="p-y"><strong>Public</strong> API access</li>
        </ul>

        <button class="btn btn-lg btn-primary btn-block">
          Start <span class="visible-lg-inline">a personal account</span>
        </button>
      </div>

      <div class="col-sm-4 p-x m-b-lg">
        <div class="p-x">
          <h6 class="text-muted text-uppercase m-b">Business</h6>
          <img class="m-b" src="assets/startup-16.svg">
          <p>The perfect sized plan for small businesses to get started.</p>
        </div>

        <ul class="list-unstyled list-bordered text-left m-y-md">
          <li class="p-y"><strong>100k</strong> monthly requests</li>
          <li class="p-y"><strong>24/7</strong> technical supprt</li>
          <li class="p-y"><strong>Public</strong> API access</li>
        </ul>

        <button class="btn btn-lg btn-primary btn-block">
          Start <span class="visible-lg-inline">a business account</span>
        </button>
      </div>

      <div class="col-sm-4 p-x m-b-lg">
        <div class="p-x">
          <h6 class="text-muted text-uppercase m-b">Corporate</h6>
          <img class="m-b" src="assets/startup-17.svg">
          <p>An unlimited plan that will scale infinitely to any size project.</p>
        </div>

        <ul class="list-unstyled list-bordered text-left m-y-md">
          <li class="p-y"><strong>Unlimited</strong> monthly requests</li>
          <li class="p-y"><strong>24/7</strong> technical supprt</li>
          <li class="p-y"><strong>Public & Private</strong> API access</li>
        </ul>

        <button class="btn btn-lg btn-primary btn-block">
          Start <span class="visible-lg-inline">a corporate account</span>
        </button>
      </div>
    </div>

  </div>
</div>



<div class="block block-inverse app-footer">
 <div class="container">
    <div class="row">
      <div class="col-sm-5 m-b-md">
        <ul class="list-unstyled list-spaced">
          <li class="m-b"><h6 class="text-uppercase">About</h6></li>
          <li class="text-muted">
           We’ve been working on Go Analytics for the better part of a decade and are super proud of what we’ve created. If you’d like to learn more, or are interested in a job, contact us anytime at <a href="mailto: themes@getbootstrap.com">themes@getbootstrap.com</a>.
          </li>
        </ul>
      </div>
      <div class="col-sm-2 col-sm-offset-1 m-b-md">
        <ul class="list-unstyled list-spaced">
          <li class="m-b"><h6 class="text-uppercase">Product</h6></li>
          <li class="text-muted">Features</li>
          <li class="text-muted">Examples</li>
          <li class="text-muted">Tour</li>
          <li class="text-muted">Gallery</li>
        </ul>
      </div>
      <div class="col-sm-2 m-b-md">
        <ul class="list-unstyled list-spaced">
          <li class="m-b"><h6 class="text-uppercase">Apis</h6></li>
          <li class="text-muted">Rich data</li>
          <li class="text-muted">Simple data</li>
          <li class="text-muted">Real time</li>
          <li class="text-muted">Social</li>
        </ul>
      </div>
      <div class="col-sm-2 m-b-md">
        <ul class="list-unstyled list-spaced">
          <li class="m-b"><h6 class="text-uppercase">Legal</h6></li>
          <li class="text-muted">Terms</li>
          <li class="text-muted">Legal</li>
          <li class="text-muted">Privacy</li>
          <li class="text-muted">License</li>
        </ul>
      </div>
    </div>
  </div>
</div>

</div>





  </body>
</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- These meta tags come first. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Bootstrap Theme Example</title>

    <!-- Include the CSS -->
    <link href="dist/toolkit.min.css" rel="stylesheet">

  </head>
  <body>

<div class="jumbotron center">
     <h1>Welcome to my app!</h1>
     <% if user_signed_in? %>
          # do something
     <% else %>
       <p>
         <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
         <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
       </p>
  <% end %>  
</div>


























    <!-- Include jQuery (required) and the JS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script src="dist/toolkit.min.js"></script>
  </body>
</html>

app/views/pins/_form.html.erb
<%= form_for(@pin) do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing Pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<div id="pins" class="transitions-enabled">
  <% @pins.each do |pin| %>
    <div class="box panel panel-default">
      <%= link_to image_tag(pin.image.url(:medium)), pin %>
      <div class="panel-body">
        <%= pin.description %><br/>
        <strong><%= pin.user.email if pin.user %></strong>
        <% if pin.user == current_user %>
          <div class="actions">
            <%= link_to 'Edit', edit_pin_path(pin) %>
            <%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/pins/new.html.erb
<h1>New Pin</h1>

<%= render 'form' %>


<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<%= link_to 'Back', pins_path %>

<div class="row">
  <div class="col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading center">
        <%= image_tag @pin.image.url(:medium) %>
      </div>
      <div class="panel-body">
        <p><%= @pin.description %></p>
        <p><strong><%= @pin.user.email if @pin.user %></strong></p>

        <% if @pin.user == current_user %>
         <%= link_to 'Edit', edit_pin_path(@pin) %>
        <% end %>

      </div>
    </div>
  </div>
</div>